name: basic_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  path_provider: ^2.1.1
  flutter:
    sdk: flutter 
  intl: ^0.18.1
  connectivity_plus: ^6.1.4
  http: ^1.3.0
  sqflite: ^2.3.0
  path: ^1.9.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  geocoding: ^2.1.0
  permission_handler: ^11.0.1
  open_file: ^3.2.1
  internet_connection_checker_plus: ^2.7.2


dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/indeportes_logo.png
    - assets/images/logo_indeportes.png
    - assets/images/logo2_indeportes.png
    - assets/utils/municipios_cauca.json